"""Order 4.0 - username

Revision ID: 1703633dd70e
Revises: c1b0cd8fec06
Create Date: 2020-03-25 16:25:27.116201

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1703633dd70e'
down_revision = 'c1b0cd8fec06'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('username', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order', 'username')
    # ### end Alembic commands ###
