"""Order 2.0 - total

Revision ID: 186be233ecbd
Revises: 1703633dd70e
Create Date: 2020-03-25 16:37:57.437764

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '186be233ecbd'
down_revision = '1703633dd70e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('placed', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order', 'placed')
    # ### end Alembic commands ###
