"""Order 1.2 - toppings

Revision ID: 1f4115e706fa
Revises: 893455eb6237
Create Date: 2020-03-25 14:48:38.978015

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f4115e706fa'
down_revision = '893455eb6237'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('toppings', sa.String(length=128), nullable=True))
    op.drop_column('item', 'top0')
    op.drop_column('item', 'top1')
    op.drop_column('item', 'top2')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('top2', sa.VARCHAR(length=128), autoincrement=False, nullable=True))
    op.add_column('item', sa.Column('top1', sa.VARCHAR(length=128), autoincrement=False, nullable=True))
    op.add_column('item', sa.Column('top0', sa.VARCHAR(length=128), autoincrement=False, nullable=True))
    op.drop_column('item', 'toppings')
    # ### end Alembic commands ###
