"""Menu1.21 - Spelling

Revision ID: 27c57b07fbf0
Revises: e5ddf8e5abba
Create Date: 2020-03-23 15:33:37.815725

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27c57b07fbf0'
down_revision = 'e5ddf8e5abba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dinnerplatters', sa.Column('dinner_platter_name', sa.String(length=128), nullable=False))
    op.drop_column('dinnerplatters', 'dp_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dinnerplatters', sa.Column('dp_name', sa.VARCHAR(length=128), autoincrement=False, nullable=False))
    op.drop_column('dinnerplatters', 'dinner_platter_name')
    # ### end Alembic commands ###
