"""Menu 1.1 - Steaktoppings

Revision ID: 47faf52407b4
Revises: 51587b4216ce
Create Date: 2020-03-23 14:10:36.983745

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47faf52407b4'
down_revision = '51587b4216ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('steaktopping',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('steak_topping_name', sa.String(length=128), nullable=False),
    sa.Column('small_price', sa.Float(), nullable=True),
    sa.Column('large_price', sa.Float(), nullable=True),
    sa.Column('steak_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['steak_id'], ['sub.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('steaktopping')
    # ### end Alembic commands ###
