"""Menu 1.0

Revision ID: 51587b4216ce
Revises: ed3b4e11d293
Create Date: 2020-03-23 13:57:41.759019

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '51587b4216ce'
down_revision = 'ed3b4e11d293'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dinnerplatters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dp_name', sa.String(length=128), nullable=False),
    sa.Column('small_price', sa.Float(), nullable=True),
    sa.Column('large_price', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('extra',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('extra_name', sa.String(length=128), nullable=False),
    sa.Column('price', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sub',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sub_name', sa.String(length=128), nullable=False),
    sa.Column('small_price', sa.Float(), nullable=True),
    sa.Column('large_price', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('topping',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('topping_name', sa.String(length=128), nullable=False),
    sa.Column('pizza_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['pizza_id'], ['pizza.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('pizza', sa.Column('large_price_per_topping', sa.String(length=128), nullable=True))
    op.add_column('pizza', sa.Column('small_price_per_topping', sa.String(length=128), nullable=True))
    op.alter_column('pizza', 'large_price',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('pizza', 'small_price',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.drop_column('pizza', 'max_toppings')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pizza', sa.Column('max_toppings', sa.INTEGER(), autoincrement=False, nullable=False))
    op.alter_column('pizza', 'small_price',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('pizza', 'large_price',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.drop_column('pizza', 'small_price_per_topping')
    op.drop_column('pizza', 'large_price_per_topping')
    op.drop_table('topping')
    op.drop_table('sub')
    op.drop_table('extra')
    op.drop_table('dinnerplatters')
    # ### end Alembic commands ###
