"""Order 1.1 - top2

Revision ID: 893455eb6237
Revises: b173bfd96333
Create Date: 2020-03-25 13:46:30.712117

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '893455eb6237'
down_revision = 'b173bfd96333'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('item', 'top3')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('top3', sa.VARCHAR(length=128), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
