"""placed - items

Revision ID: ce06270c1263
Revises: d2b558730145
Create Date: 2020-03-25 17:13:08.094002

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce06270c1263'
down_revision = 'd2b558730145'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('placedorder', sa.Column('items', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('placedorder', 'items')
    # ### end Alembic commands ###
