"""Placed 1.0 - place

Revision ID: d2b558730145
Revises: 186be233ecbd
Create Date: 2020-03-25 16:45:21.089886

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2b558730145'
down_revision = '186be233ecbd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('placedorder',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('users_id', sa.Integer(), nullable=True),
    sa.Column('username', sa.String(length=128), nullable=True),
    sa.Column('total', sa.String(length=128), nullable=False),
    sa.ForeignKeyConstraint(['users_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('order', 'placed')
    op.drop_column('order', 'username')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('username', sa.VARCHAR(length=128), autoincrement=False, nullable=True))
    op.add_column('order', sa.Column('placed', sa.VARCHAR(length=128), autoincrement=False, nullable=True))
    op.drop_table('placedorder')
    # ### end Alembic commands ###
