"""Pizza insertion.

Revision ID: ed3b4e11d293
Revises: 8c84799a201e
Create Date: 2020-03-22 15:37:28.391767

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed3b4e11d293'
down_revision = '8c84799a201e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pizza',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pizza_name', sa.String(length=128), nullable=False),
    sa.Column('small_price', sa.Float(), nullable=False),
    sa.Column('large_price', sa.Float(), nullable=False),
    sa.Column('max_toppings', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pizza')
    # ### end Alembic commands ###
